name: Prep6
channels:
        - conda-forge

dependencies:
        - python=3.6
        - numpy
        - scikitlearn
        - opencv
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
